### ISSUE TITLE
Issue with modifiers keys 

### ISSUE THREAD

**Issue by ask9027** [Julow/Unexpected-Keyboard#439] opened 2023-08-19 13:24 UTC
No modifier keys are sent to vscode while use in  [Termux-X11](https://github.com/termux/termux-x11) 

like when i press only `ctrl` it not send to any keycode not only in termux-x11 but also in other android app.

https://github.com/Julow/Unexpected-Keyboard/assets/61283438/b7a6b8c8-db7f-4194-9e84-ad5208ea3f0b

https://github.com/Julow/Unexpected-Keyboard/assets/61283438/eaf58cee-d896-408e-8265-8b01197b775e

Expected Behavior:
    Send key event down while key pressed or hold then key event up. So it can be recognised that key is pressed or hold.

**Comment by Julow** [comment] 2023-08-19 22:08
Might be related to https://github.com/Julow/Unexpected-Keyboard/issues/30

The keyboard sends down and up events for the modifiers when other keys are pressed. What problems is this causing ?

**Comment by ask9027** [comment] 2023-08-19 23:47
i not able to use multi selection cursor by `ctrl+mouseclick` in that app while i hold ctrl or pressed once.

**Comment by Julow** [comment] 2023-08-20 08:12
Interesting use case! This requires a bit of implementation work.

Keys are handled and sent to the application here https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyEventHandler.java#L35 (with `send_key_down_up`).
The problem is only "up" events are ever handled. The "down" events are not passed to `KeyEventHandler` but they exist in `Pointers` (https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/Pointers.java#L526), more arguments should be passed (eg. modifiers).

Are you interested in implementing it?

**Comment by ask9027** [comment] 2023-08-20 09:23
> Interesting use case! This requires a bit of implementation work.
> 
> Keys are handled and sent to the application here https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyEventHandler.java#L35 (with `send_key_down_up`). The problem is only "up" events are ever handled. The "down" events are not passed to `KeyEventHandler` but they exist in `Pointers` (https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/Pointers.java#L526), more arguments should be passed (eg. modifiers).
> 
> Are you interested in implementing it?

well it is excellent if implemented.

**Comment by Julow** [comment] 2023-08-26 21:42
The "down" event are now passed to the right place: f4c11d9

**Comment by ask9027** [comment] 2023-08-27 01:37
> The "down" event are now passed to the right place: [f4c11d9](https://github.com/Julow/Unexpected-Keyboard/commit/f4c11d99ed589c53229bf70d31ff71b8ac3e3ef1)

does it releted to this issue? I tried latest build after this commit but modifiers keydown not send when it is pressed or hold. It should send keydown event when it is pressed or hold like physical keyboard as i tested in my devices physical keyboard send a keydown event when any modifier key (ctrl,alt, meta) is pressed , it also send shift keydown when it is pressed or hold.

**Comment by Julow** [comment] 2023-08-27 15:19
As I said above, a technical constraint was the lack of a "down" event in the `KeyEventHandler` class. I meant to notify that this issue is now a bit simpler to fix.

**Comment by ask9027** [comment] 2023-09-25 02:39
> As I said above, a technical constraint was the lack of a "down" event in the `KeyEventHandler` class. I meant to notify that this issue is now a bit simpler to fix.

please fix this issue.🙏

**Comment by Splizard** [comment] 2023-11-17 11:22
An example of a use case here would be shift clicking to expand text selection, is this possible on android when using a web-based editor?

**Comment by Julow** [comment] 2024-01-25 23:28
This should be fixed in c5f2c0b. As this changes sensitive code, I'd appreciate if you could try it.
You can find a debug build here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/7661729447

**Comment by Julow** [comment] 2024-02-01 18:53
I opened firefox within https://github.com/termux/termux-x11

**Comment by doak** [comment] 2024-02-01 21:05
Btw., you don't differ between left or right `alt` (or any other modifier), do you?

**Comment by ask9027** [comment] 2024-02-02 17:30
> @ask9027, how do you open the keyboard while browsing the site https://www.onlinemictest.com/keyboard-test/?

https://unixpapa.com/js/testkey.html#:~:text=Javascript%20Key%20Event%20Test%20Script&text=On%20most%20browsers%2C%20suppressing%20the,or%20keyup%20events%20from%20triggering.
test here in android browser

**Comment by ask9027** [comment] 2024-02-02 17:33
> This should be fixed in [c5f2c0b](https://github.com/Julow/Unexpected-Keyboard/commit/c5f2c0b727c0ef70a76e897402e0247f148553fc). As this changes sensitive code, I'd appreciate if you could try it. You can find a debug build here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/7661729447

Sory i cant test it at termux-x11 due to my devices broken 😥. so i am using slow device , in this devices i cant perform any ternux-x11 task.

**Comment by Julow** [comment] 2024-02-03 19:48
@doak The meta key seems to work fine. Are you sure you are using a recent debug build such as this one : https://github.com/Julow/Unexpected-Keyboard/actions/runs/7661729447 ?

Can you also try `Alt` ?

**Comment by Julow** [comment] 2024-02-04 22:43
The fix is released.

**Closed by Julow** 2024-02-04 22:43 UTC
