### ISSUE TITLE
Auto Completion feature

### ISSUE THREAD

**Issue by BtAbdul** [Julow/Unexpected-Keyboard#385] opened 2023-06-21 15:51 UTC
Please add auto completion feature for no coding user, who wants use it for all apps like chats etc it would be help full.

**Comment by Julow** [comment] 2023-06-22 17:18
This is a commonly requested feature that I would like to have for myself too.
I do not have enough free time to implement such a big feature. Help is welcome.

I'll close this issues as duplicate of https://github.com/Julow/Unexpected-Keyboard/issues/68

**Closed by Julow** 2023-06-22 17:18 UTC
