### ISSUE TITLE
capslock is released automatically

### ISSUE THREAD

**Issue by alotbsol555** [Julow/Unexpected-Keyboard#556] opened 2024-02-13 09:59 UTC
possible bug: capslock is released automatically, which should not happen. casplock should be active until released manually.

steps to reproduce (autocapitalizatiol of sentences is turned off, capslock icon is on the shift key)

1. go to the github sign in page (being logged out)
2. enter some small letters in one of the fields username/password
3. go to the other field password/username
4. activate capslock **by swiping to the capslock icon** (not by long pressing shift, not by double tapping shift)
5. enter one letter
6. capslock is released automatically

this happens only when activating capslock by swiping to the icon!

this might be related to this: the shift key and the fn key are activted on starting a swipe to the corners (the keyboard flickers shortly). the 123+ key for the numpad is only activted after releasing the tap on 123+.

my guess: a part of the functionally of shift (being released after a single letter) is still active after continuing to swipe to capslock. although this happens only in special cases, which is why the above steps are a way to reproduce this.

preferred solution from a user perspective: activate shift and fn on releasing the tap instead of starting the tap: no flicker, no left over functionality.

**Comment by Spike-from-NH** [comment] 2024-02-15 10:25
Caps Lock works fine for me. My best explanation is that Unexpected sensed your gesture as a tap not a swipe, so you didn't get Caps Lock at all. Solutions: ➊ Use it more and learn what you need to do to perform a swipe; or ➋ go into Settings and change the amount of movement that defines a swipe.

Related:
① Shift key darkens when Shift or Caps Lock is active. The legend color changes color to show which one. This indication is too subtle for me; I can't tell at a glance which one is active. RED for Caps Lock?
② Caps Lock cancels if I rub out a typo. This isn't what I want.

**Comment by Spike-from-NH** [comment] 2024-02-15 19:10
Yes, seems like a "feature" of the website rather than of Unexpected, which surely doesn't care what the destination of its output is! I'll let @Julow take the next guess…

**Comment by Julow** [comment] 2024-02-17 10:56
I fail to reproduce the bug yet but I can see that caps lock is disabled when I delete a character (when first activated with the caps lock button). There seems to be unintended interaction between the caps lock button and auto-capitalisation, though that seems unrelated to your bug that happens in a password field with no auto-capitalisation.

**Comment by Julow** [comment] 2024-02-17 11:07
Caps lock can be implemented in a way that do not interfere with auto-capitalisation but it has the weird effect of allowing shift and caps lock to be enabled or locked independently at the same time.
Can you try with this debug build? https://github.com/Julow/Unexpected-Keyboard/actions/runs/7941223596

**Comment by Anarchtism** [comment] 2024-02-23 02:53
This bug also effects the note-taking app Obsidian. I don't mind the strange behavior of the debug build as a tradeoff for it working though because I do quite a lot of typing and text manipulation in Obsidian.

**Comment by Julow** [comment] 2024-03-03 16:15
I've found a variant of this bug that I can easily reproduce: Enable caps lock, type "A.", type delete, caps lock is disabled.
This should be fixed by 5e5937b.

Can you check whether it fixes your problem ? Debug build: https://github.com/Julow/Unexpected-Keyboard/actions/runs/8131473950

**Comment by Anarchtism** [comment] 2024-03-03 16:23
> Can you check whether it fixes your problem ? Debug build: https://github.com/Julow/Unexpected-Keyboard/actions/runs/8131473950

Works well for me! Great work.

**Comment by Julow** [comment] 2024-03-03 19:12
Thanks you both for confirming :)

**Closed by Julow** 2024-03-03 19:12 UTC
