### ISSUE TITLE
[BUG] Keyboard size scaling not consistent between portrait & landscape.

### ISSUE THREAD

**Issue by 0xlne** [Julow/Unexpected-Keyboard#86] opened 2022-02-26 18:57 UTC
Unexpected Keyboard Version: 1.13.0
Android version: 12
Device: Galaxy Fold 3

Use case:
Setting the keyboard size in settings scales the keyboard properly in portrait mode, but doesn't affect the scaling in landscape mode. The scaling was correct in the previous version (1.12.0).
This commit? c05fdea76554a8e95a8c63f5bb72ca9e0003a382

**Comment by Julow** [comment] 2022-02-26 19:37
Thanks for the report. Yes the scaling option isn't working in landscape mode since this commit. I intended to continue working on this before the release but decided to delay it. This was a bit dumb, sorry for the regression.

**Comment by Julow** [comment] 2022-02-27 14:34
Should be fixed (23685dd).

**Closed by Julow** 2022-02-27 14:34 UTC
