### ISSUE TITLE
Please consider increasing space between keys.

### ISSUE THREAD

**Issue by krystean** [Julow/Unexpected-Keyboard#26] opened 2022-01-14 18:30 UTC
The keys are too close to each other. I find that this makes me underestimate where to tap when typing fast thus making me commit more errors.

If you look at some of the popular keyboards, they have at least double the space between keys and at least four times between rows. It's like they're abiding to some keyboard design template which leads me to believe it must be working.

Thank you!

**Comment by Julow** [comment] 2022-01-15 19:28
Thanks for the suggestion. Currently, tapping in between the keys will hit the nearest key, on purpose. I noticed that the calculation of the position of the keys was slightly off compared to the hit box, especially for the bottom row, could this be the cause of some of your errors ? (fixed in 833dfa3)

Adding more space between the keys would be an interesting option to add.

**Comment by krystean** [comment] 2022-01-20 16:26
I'm not sure but yep, could be. I'll wait for the next FDroid update to see if there's an improvement. Thanks!

**Comment by Julow** [comment] 2022-01-30 23:07
Options to control the spacing between the keys will be present in the next release (2d2f0dd).

However, the "hit box" of the keys didn't change, there is no space between the key that do not belong to any key. Please re-open if this doesn't work for you.

**Closed by Julow** 2022-01-30 23:07 UTC

**Comment by krystean** [comment] 2022-02-06 18:30
Thank you! I've just downloaded the release and it's working great!
Ah, so it's only cosmetic? I guess it's no problem since it can work as a typing aid.

**Comment by Julow** [comment] 2022-02-06 21:10
Re-open if it still doesn't improve your typing after a few days of testing.
