### ISSUE TITLE
Clipboard need an new feature....

### ISSUE THREAD

**Issue by pratikmengal206** [Julow/Unexpected-Keyboard#473] opened 2023-09-18 17:22 UTC
As we all know the clipboard is an basic and most useful feature in our daily usage, therefore I would like to suggest that to add this basic feature to this keyboard, This thing will make it beast 💪 🔥🔥🔥🔥🔥

**Comment by Validbit** [comment] 2023-09-21 16:22
Not sure what you mean - you use it as a computer keyboard: Ctrl+C, Ctrl+V (Ctrl+X) was it something else? (look for existing issues and reference them here if needed)

**Comment by pratikmengal206** [comment] 2023-09-21 16:58
I mean you can evaluate that feature to next level like gboard provides the
clipboard which can store a previously copied things for short time like
recently copied things, i think it will be performance boosting thing for
mobile coders....
       Consider like it can be used as in situation like we have to write
particular part of code several times but, sometimes we have to copy 2-3
different segments of code at same time. instead of finding that different
segments of code in hole source code we can get it in recent copied section
👍

i have attached screenshots also for better understanding.......

**Comment by Julow** [comment] 2023-09-21 17:51
This might be the most requested feature!

I'll close this issue as duplicate of: https://github.com/Julow/Unexpected-Keyboard/issues/275 https://github.com/Julow/Unexpected-Keyboard/issues/239 https://github.com/Julow/Unexpected-Keyboard/issues/195

We just need someone to spend the time and implement it.

**Closed by Julow** 2023-09-21 17:51 UTC
