### ISSUE TITLE
[Feature] Add a Toast/Pop-Up when changing layout

### ISSUE THREAD

**Issue by OilSubjectLoss7** [Julow/Unexpected-Keyboard#841] opened 2024-12-20 18:36 UTC
so you can tell which layout are you using?

**Comment by Julow** [comment] 2024-12-21 10:17
Duplicate of: https://github.com/Julow/Unexpected-Keyboard/issues/664
We only need a volunteer for doing the work :)

**Closed** 2024-12-27 06:15 UTC
