### ISSUE TITLE
Copying an image crashes Unexpected Keyboard

### ISSUE THREAD

**Issue by MarGar12** [Julow/Unexpected-Keyboard#795] opened 2024-11-03 10:37 UTC
Crash Trace:
>FATAL EXCEPTION: main
Process: juloo.keyboard2, PID: 5431
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
	at juloo.keyboard2.g.a(SourceFile:26)
	at juloo.keyboard2.f.onPrimaryClipChanged(Unknown Source:2)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:411)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0(ClipboardManager.java:103)
	at android.content.ClipboardManager$1.$r8$lambda$ZBnZ9kLEDHJ9Wf9KWTWi217Hd24(Unknown Source:0)
	at android.content.ClipboardManager$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)

There's also no toggle to keep "Recently copied text" on, it turns off everytime and I find it kind of inconvenient :v 
Also pasting a website link in a browser causes a crash and clears the clipboard

**Comment by Julow** [comment] 2024-11-03 22:24
Thanks for the issue, this might be the same bug as https://github.com/Julow/Unexpected-Keyboard/issues/789, which is fixed.

> There's also no toggle to keep "Recently copied text" on, it turns off everytime and I find it kind of inconvenient

Let's keep this issue open until this is addressed.

**Comment by Yogesh-B** [comment] 2024-11-23 16:53
I am using android 14. there is new feature that after taking screenshot it gets saved in clipboard and we can paste it directly anywhere(I tried pasting in whatsapp). Gboard is pasting image without issue. In unexpected keyboard, whatsapp just hangs.  I also tried in gmail app, pasting image works fine in gmail app.  github mobile is not pasting the image neither using gboard nor unexpected kb.

**Comment by Julow** [comment] 2024-12-05 23:13
The persistence bug should be fixed in dc922b0.

@Yogesh-B I can't reproduce the issue. On my device, I can't paste an image into whatsapp or other apps with any keyboard. I don't have the gmail app though. Are you doing a long press into the text area then paste ?

**Comment by NorbiPeti** [comment] 2024-12-13 22:23
The debug build in #789 fixed the crash when taking a screenshot on Android 14 for me. I can also paste images into Discord with Ctrl+V or the Paste option. I can't seem to paste it in Nextcloud Notes or FairEmail though (they don't do anything), but I'm guessing the apps themselves should be handling that part. I *can* paste the image as text with Ctrl+Shift+V anywhere, although that's less useful.

**Comment by Julow** [comment] 2024-12-14 10:52
Thanks for your feedback :) I'll close this issue as it is complete now.

**Closed by Julow** 2024-12-14 10:52 UTC
