### ISSUE TITLE
Disable/Toggle Tab (input field switch) for cursor movement on Spacebar

### ISSUE THREAD

**Issue by Validbit** [Julow/Unexpected-Keyboard#432] opened 2023-08-14 12:36 UTC
When I've seen the feature (spacebar cursor movement) was implemented some time ago I was grateful, yet to this day I couldn't really use it, because its behaviour of acting like Tab when scrolling too far (both accidentally/intentionally: line start/end quickly) makes it difficult to use (at least in my experience over the time)

The behaviour seems similar to the cursor movement key that is implemented, where this behaviour is very handy.

Do you think this could be a togglable option or disabled (for spacebar only, not the dedicated key)

**Comment by Julow** [comment] 2023-08-15 18:05
This is an unintended behavior and should be changed, not optional.

The slider movement is repeatedly sending left/right arrow keys instead of modifying the cursor position directly to be useable in Termux.
A solution might be to add a new kind of key that modifies the cursor position instead of sending arrow keys. It would send an arrow key if it's not possible to change the cursor position (eg. on Termux).

**Comment by Julow** [comment] 2023-08-17 10:54
I've implemented all of that in 5123ce5.

**Comment by Julow** [comment] 2023-08-24 22:11
Thanks for the report. This indeed seems like an overlooking. When a modifier other than shift is active, it should fallback to arrow keys like before.

**Comment by doak** [comment] 2023-08-25 17:42
I played around with the current implementation  bit. Would be cool if it would allow to extend/shrink a selection on both sides.

Regarding behaviour for selections: Is it intended that you don't need to hold shift to change the selection? This way you can't exit select mode with a spacebar slide.
I was quite happy with previous behaviour: ;)
Holding shift (respectively pressing shift in advance) and a slide to select text was imho quite convinient and intuitive. And it was possible to select to the left.

**Comment by Julow** [comment] 2023-08-25 18:27
> Is it intended that you don't need to hold shift to change the selection? This way you can't exit select mode with a spacebar slide.

Yes, it's intended. The Shift state could change due to automatic, which clears the selection. You can clear the selection with the regular arrow keys.
You need to hold shift to start the selection but until it's cleared the shift state doesn't matter. It's still possible to select to the left, right ?

**Comment by Julow** [comment] 2023-08-25 18:29
> Would be cool if it would allow to extend/shrink a selection on both sides.

This is interesting. How to make this intuitive ?

**Comment by doak** [comment] 2023-08-25 19:26
> It's still possible to select to the left, right ?

Nope. It just moves the one-char-width selection to the left. I.e. you need to reselect to the right afterwards again.

> The Shift state could change due to automatic

Haven't experienced this up to now. Inside which app does that happen?

**Comment by doak** [comment] 2023-08-25 19:40
> > Would be cool if it would allow to extend/shrink a selection on both sides.
> 
> This is interesting. How to make this intuitive ?

What about extending in the direction of slide when Shift had "touched" again? And shrink (afterwards) in the opposite direction.
Let's assume previous behaviour: Cursor was either at right or left border of selection. This made it possible to shrink again from that side.
This idea changes this to always extend first (i.e. jump the curser to the corresponding border). If you want to shrink from the left, you need first extend to the left (slide left) and then slide to the right as far as you want. As long as one slide (or shift is hold/stixky) the shrink/extend should stay the same (i.e. a change in direction only happens if all keys has been released including sticky Shift).

That sounds quite intuitive to me. But implementation effort may be a bit I guess. ;)

**Comment by Julow** [comment] 2023-08-26 14:33
The information might already arrive at the right place: https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyEventHandler.java#L45
That's not guaranteed, though, as "double tap for capslock" might interfere. I'm planning a "key down" event at this point to fix https://github.com/Julow/Unexpected-Keyboard/issues/441 which would be an alternative.

**Comment by Julow** [comment] 2023-08-26 21:39
The "key down" event is implemented in f4c11d9.

**Comment by Julow** [comment] 2023-08-26 21:49
The Ctrl regression is fixed in 9b917e7.

@doak Could you open a new issue for your slider ideas?

**Closed by Julow** 2023-08-26 21:49 UTC
