### ISSUE TITLE
Keypress vibration not working

### ISSUE THREAD

**Issue by XDMelone333** [Julow/Unexpected-Keyboard#360] opened 2023-05-07 09:43 UTC
I've read through a few issues regarding the vibrations already, but i can't seem to find why it doesn't work for me. I have the vibrations enabled in the keyboards settings, I made sure to enable touch vibrations in my android settings and it just won't work. 
It also works completely fine with my standard Samsung Keyboard.
I'm running the latest version of Unexpected Keyboard from the F-Droid store, I'm on a Samsung Galaxy A52s 5G running Android 13 and OneUI 5.1.
Hope someone can help me with this 👍

**Comment by Rodrigodd** [comment] 2023-05-07 13:05
I have the same issue in Samsung Galaxy A22, Android 13, OneUI 5.0.

**Comment by Spike-from-NH** [comment] 2023-05-11 15:51
Same problem on various Samsungs running Android 8 and 9. Has never worked for me. Though I'd prefer key-click sound; take a look at how Hacker's Keyboard did it.

**Comment by XDMelone333** [comment] 2023-05-11 17:01
> Same problem on various Samsungs running Android 8 and 9. Has never worked for me. Though I'd prefer key-click sound; take a look at how Hacker's Keyboard did it.

I'm someone to prefer a vibration response, but a sound response would be better than nothing.
Maybe if this is too much effort to fix, we could get an optional sound response in the apps settings?

**Comment by Ivan6018** [comment] 2023-05-26 05:13
I have a xiaomi redmi note 9 running miui 13 and android 12. in the system settings, vibration is enabled, power saving mode is turned off but there is no vibration

**Comment by JackDotJS** [comment] 2023-05-27 14:24
i once had a similar issue where the vibration randomly stopped working in the middle of typing something. the only thing that would fix it was a complete device restart... but so far, it's only happened once.

Google Pixel 7 Pro with GrapheneOS. Android 13

**Comment by Julow** [comment] 2023-06-03 09:16
The vibration option is improved in 69e0b4c. The 3 new settings (Strong, medium or light) should work in more situation than the previous (now named System).

I'm interested in feedback. Debug APK available here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/5162932148

**Comment by Spike-from-NH** [comment] 2023-06-03 10:29
To me on Samsung J7 (2018, Android 8), "strong" was perfect, not terribly strong; medium and light were imperceptible.

Thanks for this work; I also experimented with new wider range for legend size. (130% suits me; I had asked for 140% but with my settings, the legends collide.)

**Comment by Julow** [comment] 2023-06-04 21:35
I slightly increased the strength ([debug APK here](https://github.com/Julow/Unexpected-Keyboard/actions/runs/5171300640)). Thanks for the feedback, I'll close this issue.

**Closed by Julow** 2023-06-04 21:35 UTC

**Comment by Spike-from-NH** [comment] 2023-06-05 00:51
Now "strong" is very strong, still can't sense "medium". Perhaps offer a slider like margin and other options?

**Comment by Spike-from-NH** [comment] 2023-06-05 09:48
Debug APK No.2 is now installed on a Samsung Tab A 8 (old) with Android 10; cannot sense "light," can barely feel "medium," can feel and hear "strong." I prefer the "strong" before your most recent adjustment.

**Comment by Julow** [comment] 2023-08-02 19:03
A slider is not the best because of the "system" and "disabled" cases. I've increased the values by 50%. (4abea0e)

**Comment by XDMelone333** [comment] 2023-08-02 19:11
> A slider is not the best because of the "system" and "disabled" cases. I've increased the values by 50%. ([4abea0e](https://github.com/Julow/Unexpected-Keyboard/commit/4abea0e8780f0a501706db555665ac951e82aaf9))

How about this?
The option to select between "disabled", "system" and "slider". If "slider" is selected a slider appears under the selector.

**Comment by Spike-from-NH** [comment] 2023-08-02 22:06
Agree with @Julow that a slider alone won't suffice, but also with @XDMelone that a fancier UI could provide access to all the options.

**Comment by Julow** [comment] 2023-08-04 19:29
I'm not keen on implementing a more complex option. The app must remain light.

If the problem is that the "strong" setting is not strong on some devices, perhaps the physical strength of the vibrator could be queried to adjust the value ? I did not find a way to do that but on API >= 29, this different API might help: https://developer.android.com/reference/android/os/VibrationEffect?hl=en

**Comment by JackDotJS** [comment] 2023-08-05 01:25
i dont see what harm there is in simply having two rows of options in the UI. 

similar to what @XDMelone333 suggested:
1. 3 radio buttons (or even just a dropdown menu): disabled, system default, custom
2. a slider, which is disabled (or better yet, just hidden) unless "custom" is selected

even if that's technically 4 options to manage, i find it extremely difficult to imagine it would bloat the app *that* badly lol. the APK is already just under 300 KB, which is INSANELY lightweight to begin with.

**Comment by Julow** [comment] 2023-08-05 14:08
More buttons means more translations. There's no other such option, so it would also takes time to implement.
The slider's value wouldn't mean the same thing on different devices, which will also bring similar bug reports. 

I'd rather wait for someone to investigate other solutions.

**Comment by Spike-from-NH** [comment] 2023-08-05 17:18
A quibble, @XDMelone333's solution is a bit too fancy: A slider set to the minimum means the user wants vibration disabled.

**Comment by JackDotJS** [comment] 2023-08-05 20:20
i can understand the concern about localization. i don't have any good solutions for that, unfortunately. that said...

> The slider's value wouldn't mean the same thing on different devices.

isn't that the whole point of the slider...? it allows people to adjust it based on their needs, *and* the capabilities of their devices.

> A quibble, @XDMelone333's solution is a bit too fancy: A slider set to the minimum means the user wants vibration disabled.

this would also work. imo though, having a more obvious "disabled" option would be better for UX. it might not be obvious to some that lowering the slider all the way would disable vibration.
