### ISSUE TITLE
Cannot utilize functions like Ctrl+c if keyboard is not open.

### ISSUE THREAD

**Issue by Alphega** [Julow/Unexpected-Keyboard#494] opened 2023-11-23 11:25 UTC
There should be an option in the keyboard's settings enabling which shows a notification on clicking which opens unexpected keyboard. This option will be really helpful, please consider implementing it.

**Comment by Spike-from-NH** [comment] 2023-11-23 22:12
It is Android or the active app that calls for display of the soft keyboard (for example, Unexpected Keyboard). If Unexpected is going to activate without being called for, I'd want to know by what criteria. Otherwise, you risk Unexpected popping up when it's not wanted.

**Comment by Alphega** [comment] 2023-11-24 09:33
> It is Android or the active app that calls for display of the soft keyboard (for example, Unexpected Keyboard). If Unexpected is going to activate without being called for, I'd want to know by what criteria. Otherwise, you risk Unexpected popping up when it's not wanted.

What I mean is that there should be an option in the settings of the keyboard. When that option is turned on, a notification in the notification bar wil be sent to the user. If the user cicks that notification, the keyboard opens. The notification should not disapear unless the option is turned off from the settings of the keyboard.

**Comment by Spike-from-NH** [comment] 2023-11-24 14:17
Yes, a button in the Notification "windowshade" would let you raise the keyboard at will. Users who don't want this complication could block Unexpected from sending Notifications.

**Comment by Julow** [comment] 2023-11-25 16:49
This might not be possible since Android 11. Hacker's Keyboard is known to have this feature and it's been broken since Android 11.

**Comment by Julow** [comment] 2024-01-15 19:09
This is a duplicate of https://github.com/Julow/Unexpected-Keyboard/issues/496 https://github.com/Julow/Unexpected-Keyboard/issues/71 https://github.com/Julow/Unexpected-Keyboard/issues/392 https://github.com/Julow/Unexpected-Keyboard/issues/69
An implementation is proposed in https://github.com/Julow/Unexpected-Keyboard/pull/497

**Closed by Julow** 2024-01-15 19:09 UTC
