### ISSUE TITLE
Unwanted characters present on the keyboard after configuring my custom layout

### ISSUE THREAD

**Issue by evoneon** [Julow/Unexpected-Keyboard#564] opened 2024-02-18 16:46 UTC
Hi there!
This app is essential to my daily life. I thank you so much for bringing this gem to us.
Here is a behaviour I cannot explain and I would love a solution for it.
Cheers!

**Context**
Version : 1.26.0
Device : Android 13 (Samsung Galaxy S22)
Today's date : 2024 February 18

**Steps to reproduce**
1. Edit the default layout which is US QWERTY
2. Remove many of the unwanted keys in the XML configuration file

**Observed result**
- Some unwanted characters are present on some keys despite the changes in the XML file
- These characters do not appear in the XML configuration file and I do not understand where they are coming from
- See the attachments section for the specific characters concerned

**Expected result**
- Beside the bottom row that seems to require a specific configuration, the other rows should match precisely the XML configuration file

**Attachments**
- My XML configuration file missing the unwanted characters : [My XML config file - Unexpected Keyboard.txt](https://github.com/Julow/Unexpected-Keyboard/files/14323489/My.XML.config.file.-.Unexpected.Keyboard.txt)
- Screenshot of my final layout with the unwanted characters : ![My XML Layout - Unexpected Keyboard](https://github.com/Julow/Unexpected-Keyboard/assets/45544143/045032ea-ab4b-4068-be2c-1ccc871d4246)

**Comment by Spike-from-NH** [comment] 2024-02-18 17:50
No indeed, there is nothing in your XML file that calls for these characters.

Normally, if you use the "Add keys to the keyboard" option (gear icon above `Fn`), they go where the XML has something like `key3="loc ..."`. Perhaps this is where they go by default. Please go into that selection and be sure these characters are unchecked.

**Comment by Julow** [comment] 2024-02-18 19:03
Thanks for the well written issue!

This is intended though I understand you'd want an option to control this. Especially that accented letters are easier to type since https://github.com/Julow/Unexpected-Keyboard/pull/559.

The keyboard will add the characters needed to type all the languages installed on your device, on every layouts. This is defined here: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/method.xml

For example, `accent_grave:à:è:ù@a` specifies that `accent_grave` (the dead-key) should be added, if possible on the same key as `a`, except if `à`, è` and `ù` are already on the layout.

There might be a bug though, `é` and `accent_aigu` shouldn't be on the layout at the same time. What are your installed languages ?

**Comment by Spike-from-NH** [comment] 2024-02-18 19:11
@Julow beat me to my response, which had been to concede confusion.

Adding characters based on locale may be right for built-in layouts but, when a custom layout is in effect, the feature seems more likely to confound the user than help, even if there were a way to disable it.

**Comment by evoneon** [comment] 2024-02-19 12:48
My system languages are the following :
- English (Canada)
- French (Canada)

My Samsung keyboard's languages are the following :
- English (US)
- French (Canada)

So the é and ç characters make sense. After a few tries, I managed to hide them using « loc é » and « loc c » which made me quite happy! 🥳🎉😎

The only unwanted characters remaining now are the € and £ which aren't in the XML file nor checked in the "additional buttons" settings.

After reading the links you posted above, I noticed both the £ and € seem to be associated with the en-GB language (Image 1). I do not have this one enabled on my device but I noticed this following settings (Image 2) :
- Image 1 : Special characters associated to languages <img width="1530" alt="Capture d’écran, le 2024-02-19 à 07 35 30" src="https://github.com/Julow/Unexpected-Keyboard/assets/45544143/2c134c94-1562-40b5-a940-f2e291fe35e4">
- Image 2 : My keyboards ![1000005407](https://github.com/Julow/Unexpected-Keyboard/assets/45544143/0520512f-b825-45a1-a063-495ba65bf5af)

For some unknown reasons, the English language is associated to the United Kingdom and french with Switzerland. I'm wondering if there is a link between my Unexpected Keyboard showing UK, and the language us-GB being associated with the £ and € characters? This is the only hypothesis I have so far 🤨🤓

**Comment by Julow** [comment] 2024-02-24 10:58
Should be fixed in d7e5040. You can find a debug APK here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/8030070025

**Comment by Julow** [comment] 2024-03-09 10:38
The fix has been released.

**Closed by Julow** 2024-03-09 10:38 UTC

**Comment by AMTQ** [comment] 2024-03-09 18:41
Thanks for the clarification @Julow. I was struggling with this issue and trying to "remove" the unwanted modifiers by placing a keyX="space" for the position in question, but obviously that does not work but just shifts for example the accent_grave elsewhere 😄 so bottom line: place these modifiers somewhere out of the way? Or is there another way to deal with it?

**Comment by Julow** [comment] 2024-03-10 19:18
@AMTQ What are the languages installed in your device ?

**Comment by AMTQ** [comment] 2024-03-10 19:43
German and French.

10.03.2024 20:18:55 Jules Aguillon ***@***.***>:

**Comment by Julow** [comment] 2024-03-10 20:03
`accent_grave` should disappear if you have `à` and `è` on your layout in the last version. (Before, you also needed `ù`)

Do you intent to make a layout without any of these ? This is not possible at the moment, the issue is: https://github.com/Julow/Unexpected-Keyboard/issues/388

**Comment by AMTQ** [comment] 2024-03-10 21:06
Yes, that did the trick, thanks! With AOSP I did always change between the two languages, now I have just focused on german but with french letters available, see picture.
![Screenshot_20240310-220401_Vivaldi~(1)](https://github.com/Julow/Unexpected-Keyboard/assets/12964408/dbc134a8-576a-4a64-baa0-357bd41094ad)


It's a really cool app btw!

**Comment by Julow** [comment] 2024-03-10 21:59
Nice layout :) Don't you have any problem typing â and à on the border of the screen ?

**Comment by AMTQ** [comment] 2024-03-12 23:06
I don't know yet, as I use french rarely, maybe once or twice a week. But I think it should be fine, when writing with two thumbs it's ok... à voir, spontanement j'en connais même pas de mot avec â?!? 🤔
