### ISSUE TITLE
Custom keyboard crashes Unexpected (Debug)

### ISSUE THREAD

**Issue by JapanYoshi** [Julow/Unexpected-Keyboard#688] opened 2024-07-03 15:56 UTC
I was editing my keyboard, but when I paste the layout, it causes Unexpected Keybeard to crash, and I can’t tell why. The XML is valid so I don’t know what’s going wrong.

Keyboard layout:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<keyboard bottom_row="false" name="HoneyKey" script="latin">
  <modmap>
    <shift a="(" b="&gt;" />
    <shift a=")" b=">" />
    <shift a="[" b="{" />
    <shift a="]" b="}" />
    <shift a="%" b="‰" />
  </modmap>
  <row>
    <key key0="switch_numeric" key5="loc shareText" key6="alt" key7="switch_emoji" key8="ctrl"/>
    <key key0="switch_greekmath" key1="=" key5="`" key6="*" key7="\\" key8="_"/>
    <key key0="e" key5="o" key6="i" key7="x" key8="y"/>
    <key key0="r" key5="f" key6="d" key7="z" key8="k"/>
    <key key0="." key2="+" key5=":" key6="-" key7="\?" key8="’"/>
    <key key0="backspace" key6="loc " key7="delete" key8="loc change_method"/>
  </row>
  <row>
    <key width="1.5" key0="left" key5="home" key6="page_up" key7="up" key8="down"/>
    <key key0="a" key5="/" key6="j" key7="m" key8="u"/>
    <key key0="space"/>
    <key key0="s" key5="p" key6="—" key7="c" key8="l"/>
    <key width="1.5" key0="right" key5="page_down" key6="end" key7="up" key8="down"/>
  </row>
  <row>
    <key key0="config" key5="loc voice_typing" key6="meta" key7="loc superscript" key8="loc subscript"/>
    <key key0="shift" loc5="loc esc" key7="capslock" key8="loc fn"/>
    <key key0="n" key5="q" key6="g" key7="v" key8="compose"/>
    <key key0="t" key5="h" key6="b" key7="w" key8="tab"/>
    <key key0="," key5="“" key6="”" key7="!" key8=";"/>
    <key key0="&#10;" key6="switch_forward" key7="enter" key8="action"/>
  </row>
  <row>
    <key width="0.6" key0="1" key2="|" key4="["/>
    <key width="0.6" key0="2" key1="&quot;" key2="\@" key3="]" key4="♥"/>
    <key width="0.6" key0="3" key1="\#" key2="·" key3="•" key4="・"/>
    <key width="0.6" key0="4" key1="$" key2="♡" key3="⚡" key4="⌁"/>
    <key width="0.6" key0="5" key1="%" key3="√" key4="ꜜ"/>
    <key width="0.6" key0="6" key1="^" key2="⚙" key3="❤️‍🔥" key4="◉‿◉"/>
    <key width="0.6" key0="7" key1="'" key2="&amp;" key3="✨" key4="🎨"/>
    <key width="0.6" key0="8" key1="~" key2="～" key3="🧠" key4="🔨"/>
    <key width="0.6" key0="9" key1="👅" key2="(" key3="👃" key4="♻️"/>
    <key width="0.6" key0="0" key1=")"/>
  </row>
</keyboard>
```

Crash stack trace:
```
type: crash
osVersion: google/bramble/bramble:14/UP1A.231105.001.B2/2024060500:user/release-keys
package: juloo.keyboard2.debug:40
process: juloo.keyboard2.debug
processUptime: 628 + 204 ms
installer: com.android.packageinstaller

java.lang.IndexOutOfBoundsException: Index 8 out of bounds for length 6
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at juloo.keyboard2.KeyboardData.add_key_to_pos(KeyboardData.java:103)
	at juloo.keyboard2.KeyboardData.add_key_to_preferred_pos(KeyboardData.java:81)
	at juloo.keyboard2.KeyboardData.addExtraKeys(KeyboardData.java:55)
	at juloo.keyboard2.Config.modify_layout(Config.java:304)
	at juloo.keyboard2.Keyboard2.current_layout(Keyboard2.java:64)
	at juloo.keyboard2.Keyboard2.onStartInputView(Keyboard2.java:253)
	at android.inputmethodservice.InputMethodService.startViews(InputMethodService.java:2970)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2878)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:984)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:951)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:228)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:894)
```

**Comment by Julow** [comment] 2024-07-06 11:36
Thanks for the report, this is caused by 773147a and is fixed in 6021a0b.
Interesting layout!

**Closed by Julow** 2024-07-06 11:36 UTC
