### ISSUE TITLE
cant access clipboard

### ISSUE THREAD

**Issue by Hadi-M0** [Julow/Unexpected-Keyboard#508] opened 2023-12-21 11:03 UTC
how do i do that?

**Comment by Spike-from-NH** [comment] 2023-12-21 18:20
Swipe the "gear" logo on Fn to go to Settings. Tap "Add keys to the keyboard". The usual ones (Cut/Copy/Paste) are near the bottom of this list. Switch them on and they will now appear as swipes. Otherwise, you can still use the clipboard with Windows-style sequences, such as Ctrl,V for Paste.

**Comment by Julow** [comment] 2023-12-21 18:46
I think this issue is about the clipboard history feature found in other keyboards. This is a commonly requested feature and I'll close as a duplicate of https://github.com/Julow/Unexpected-Keyboard/issues/195

**Closed by Julow** 2023-12-21 18:46 UTC
