### ISSUE TITLE
Issue regarding shift button 

### ISSUE THREAD

**Issue by Dark-Devil09** [Julow/Unexpected-Keyboard#512] opened 2023-12-23 16:43 UTC
Is there a way to use shift in this keyboard because I can't find either by default or can't find in add buttons category in the settings menu too

**Comment by Julow** [comment] 2023-12-23 19:21
In what application do you observe this ? This could be related to https://github.com/Julow/Unexpected-Keyboard/issues/30#issuecomment-1048221972

**Comment by Dark-Devil09** [comment] 2023-12-24 01:29
> In what application do you observe this ? This could be related to https://github.com/Julow/Unexpected-Keyboard/issues/30#issuecomment-1048221972

I am not getting to use shift key for any application. Most probably the keyboard doesn't offers the shift key features.

**Comment by Dark-Devil09** [comment] 2023-12-24 01:41
I have worked with many keyboard like hacker's keyboard codeboard etc. But no keyboard offers all the required modified keys. This keyboard currently offers only the following keys
- Ctrl
- Alt
- esc
- meta
However shift key is missing. if this feature will be added it would really useful

**Comment by Dark-Devil09** [comment] 2023-12-24 01:42
I have worked with many keyboard like hacker's keyboard codeboard etc. But no keyboard offers all the required modified keys. This keyboard currently offers most of the keys like :
- Ctrl
- Alt
- esc
- meta
- tab
However shift key is missing. if this feature will be added it would really useful.

**Comment by Julow** [comment] 2023-12-26 10:35
In what application do you need the shift key? I need to know this as the keyboard has a shift key.

**Comment by Dark-Devil09** [comment] 2023-12-27 05:07
> In what application do you need the shift key? I need to know this as the keyboard has a shift key.

VHE editor

**Comment by lux5am** [comment] 2023-12-31 08:53
i need this to to select text on various text. Us*ng android hold tap to select isnt always accurate and sometimes make a mess. For example select text in addons for firefox like ublock, tampermonkey etc.

**Comment by Dark-Devil09** [comment] 2024-01-01 16:58
> In what application do you need the shift key? I need to know this as the keyboard has a shift key.

if this keyboard already have the shift button how do i use it since i am not getting it. Please reply

**Comment by Julow** [comment] 2024-01-01 20:25
The shift key (the key above the "123+" key on the left) can be used to select text (with the arrows or by sliding on the space bar).

It doesn't work with some apps and that's a long standing issue: https://github.com/Julow/Unexpected-Keyboard/issues/30#issuecomment-1048221972
I'll add this to the roadmap to 1.26.1.

**Comment by lux5am** [comment] 2024-01-01 21:04
> The shift key (the key above the "123+" key on the left) can be used to select text (with the arrows or by sliding on the space bar).
> 
> It doesn't work with some apps and that's a long standing issue: [#30 (comment)](https://github.com/Julow/Unexpected-Keyboard/issues/30#issuecomment-1048221972) I'll add this to the roadmap to 1.26.0.

There's no shift button I tried many apps. Digging all the options in unexpected keyboard. There's a double tap shift for caps lock option. There's nothing else with word "shift".

![IMG_20240102_050243](https://github.com/Julow/Unexpected-Keyboard/assets/110870661/6fbdd270-7ae7-4f1f-b99d-292982afcefb)

**Comment by Julow** [comment] 2024-01-02 11:37
This is the shift key:
![2024-01-02-12-35](https://github.com/Julow/Unexpected-Keyboard/assets/2310568/d2f1ef83-cf39-40b3-9490-6921db68d7c5)

For example, Shift+arrows selects text. The issue is that it doesn't work with some apps.

**Comment by Dark-Devil09** [comment] 2024-01-02 12:28
> This is the shift key:
> ![2024-01-02-12-35](https://github.com/Julow/Unexpected-Keyboard/assets/2310568/d2f1ef83-cf39-40b3-9490-6921db68d7c5)
> 
> For example, Shift+arrows selects text. The issue is that it doesn't work with some apps.

Can we expect a solution of the issue ?

**Comment by Julow** [comment] 2024-01-15 18:53
This is an important bug and I plan to work on fixing it.

**Comment by Julow** [comment] 2024-01-15 19:14
Might be related to https://github.com/Julow/Unexpected-Keyboard/issues/439

**Comment by Julow** [comment] 2024-01-25 23:28
This should be fixed in c5f2c0b. As this changes sensitive code, I'd appreciate if you could try it.
You can find a debug build here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/7661729447

**Comment by Julow** [comment] 2024-02-04 22:43
The fix is released.

**Closed by Julow** 2024-02-04 22:43 UTC

**Comment by Dark-Devil09** [comment] 2024-02-17 03:30
> This should be fixed in [c5f2c0b](https://github.com/Julow/Unexpected-Keyboard/commit/c5f2c0b727c0ef70a76e897402e0247f148553fc). As this changes sensitive code, I'd appreciate if you could try it. You can find a debug build here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/7661729447

Ya done works fine
