### ISSUE TITLE
Dark theme doesnot work :(

### ISSUE THREAD

**Issue by aveekbhat** [Julow/Unexpected-Keyboard#42] opened 2022-01-26 12:34 UTC
This is how the dark theme looks like

![image](https://user-images.githubusercontent.com/1280869/151163584-f4425a9c-8572-4497-8898-357b754ab9a4.png)

here is how the Google keyboard looks like
![image](https://user-images.githubusercontent.com/1280869/151163764-54ff1140-897f-45c8-972a-52fab9b2534d.png)

**Comment by Julow** [comment] 2022-01-26 17:35
Did you use the "Theme" option in the settings ? Tap the "Conf" symbol on the bottom-right of the "Alt" key and scroll to the bottom.

The app doesn't work well with the system theme and I'd rather fix that for the next release.

**Comment by aveekbhat** [comment] 2022-01-27 02:25
> Did you use the "Theme" option in the settings ? Tap the "Conf" symbol on the bottom-right of the "Alt" key and scroll to the bottom.
 yes i did exactly that but it didnt work :( ... BTW .. my phone is in system dark mode
 
> The app doesn't work well with the system theme and I'd rather fix that for the next release.

Thanks !!

**Comment by Julow** [comment] 2022-01-30 22:34
I couldn't reproduce the issue on the devices I have access to. I've attempted a fix (c9f7f2c) but I'll leave this open until you can try the next version.

**Comment by ZueyEnfe** [comment] 2022-02-07 05:43
still doesn't work. at least on my phone
this is how dark mode look like
![IMG_20220207_123225](https://user-images.githubusercontent.com/99162380/152730341-aff085a5-05e8-41de-873a-053a5599f5af.jpg)
and this is how black mode look like
![IMG_20220207_123247](https://user-images.githubusercontent.com/99162380/152730450-14a38222-cb96-406e-ae8c-35432ab1d68c.jpg)
it happened on my xiaomi redmi note 7 with android 10(MIUI 12.5.1.0)

**Comment by 07416** [comment] 2022-02-12 20:26
Does the dark theme apply to the settings menu?

**Comment by Julow** [comment] 2022-02-13 10:50
Xiaomi phones have unusual dark theme mechanisms, I think I fixed the issue (adb7746).

The settings menu doesn't use dark theme yet, I'll leave this issue open until it does.

**Comment by Julow** [comment] 2022-02-27 17:33
Dark theme should now work fine. The settings will use dark theme for everyone now (4ee29f3), which I think is enough to close this.

**Closed by Julow** 2022-02-27 17:33 UTC

**Comment by aveekbhat** [comment] 2022-02-28 01:24
i can confirm it works fine now !! thanks !!
