### ISSUE TITLE
add this (I don't know the names of these functions) [feature request]

### ISSUE THREAD

**Issue by Wjxfi** [Julow/Unexpected-Keyboard#274] opened 2023-01-14 14:51 UTC
I need this! it's very convenient!

https://user-images.githubusercontent.com/113500363/212477815-60008c3f-3b8b-4246-ab31-dae342f2ab75.mp4

https://user-images.githubusercontent.com/113500363/212477819-e3c432a2-9db0-4b1d-8465-b4922de064da.mp4

these two features are taken from [Openboard](https://github.com/openboard-team/openboard)

**Comment by Julow** [comment] 2023-01-14 22:37
Duplicate of https://github.com/Julow/Unexpected-Keyboard/issues/267#issuecomment-1382950791

**Closed by Julow** 2023-01-14 22:37 UTC

**Comment by Julow** [comment] 2023-01-14 22:58
It is still a duplicate. The idea has already been suggested in the past (https://github.com/Julow/Unexpected-Keyboard/issues/46) and will be considered in further development of https://github.com/Julow/Unexpected-Keyboard/issues/267.
