### ISSUE TITLE
pop up on keypress

### ISSUE THREAD

**Issue by Ejobat** [Julow/Unexpected-Keyboard#591] opened 2024-03-15 18:38 UTC
Is it possible to have the pop-up keypress feature, please? This feature was previously requested in issue #132, but it has not been implemented thus far.

**Comment by Julow** [comment] 2024-03-16 10:10
Contribution to the code welcome. I'll close this issue as duplicate of https://github.com/Julow/Unexpected-Keyboard/issues/132

**Closed by Julow** 2024-03-16 10:10 UTC
