### ISSUE TITLE
[Feature Request] Back Space swipe gesture to delete word

### ISSUE THREAD

**Issue by GarvitGothwal** [Julow/Unexpected-Keyboard#608] opened 2024-04-01 16:27 UTC
Just as it is in the google keyboard!

**Comment by Julow** [comment] 2024-04-01 22:03
This would be nice to have and is a frequently requested feature. Anyone interested in implementing it ?

I'll close this as a duplicate of https://github.com/Julow/Unexpected-Keyboard/issues/46 (oldest open issue)

**Closed by Julow** 2024-04-01 22:03 UTC
