### ISSUE TITLE
[Feature Request] Add Search Bar For Emojis

### ISSUE THREAD

**Issue by ARGENTI21** [Julow/Unexpected-Keyboard#271] opened 2023-01-13 13:28 UTC
Some keyboards out there (LG keyboard) have a search bar built into the emoji section to allow quick allocation of emoji needed.
Would be very convenient

**Comment by JackDotJS** [comment] 2023-02-15 17:59
dupe of #173 
im glad im not the only one who wants this though lol

**Comment by Julow** [comment] 2023-02-26 10:35
Closed as duplicate.

**Closed by Julow** 2023-02-26 10:35 UTC
