### ISSUE TITLE
Cant copy using ctrl c

### ISSUE THREAD

**Issue by Techlord210** [Julow/Unexpected-Keyboard#101] opened 2022-03-12 16:07 UTC
I can paste anything from clipboard with ctrl key but cant copy or cut anything fix this its really nice keyboard.

**Comment by Julow** [comment] 2022-03-12 19:11
In which applications doesn't Ctrl+c work ?

**Comment by Techlord210** [comment] 2022-03-12 19:27
> In which applications doesn't Ctrl+c work ?

I normally test keyboard on search engine let me test it on other apps too

**Comment by Julow** [comment] 2022-03-17 11:28
I found that Ctrl+C doesn't work in most text views but only when the selection starts from the beginning of the text *and* the selection wasn't made with Ctrl+A.
This doesn't seem to be caused by the keyboard but perhaps it should take care of some editing shortcuts to work around broken text views. Related: https://github.com/Julow/Unexpected-Keyboard/issues/99

**Comment by rancidfrog** [comment] 2022-09-24 16:15
I have another issue with ctrl+c, when I copy on one app and switch to another and then try ctrl+v it pastes previous text copied using another heyboard and not what I copied using unexpected keyboard

**Comment by Julow** [comment] 2022-09-24 16:59
Could it be caused by the same bug ? The first ctrl+c might have not done anything.

**Comment by Julow** [comment] 2022-11-13 15:57
I close this in favor of https://github.com/Julow/Unexpected-Keyboard/issues/242

**Closed by Julow** 2022-11-13 15:57 UTC
